version: '3'

services:
  gptweb:
    container_name: chatgpt-web-midjourney-proxy
    image: ydlhero/chatgpt-web-midjourney-proxy # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 6050:3002
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 必选
      OPENAI_API_KEY: sk-xxxx
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL:
      # 访问权限密钥，可选
      AUTH_SECRET_KEY:
      # midjourney 服务器地址，可选 可用下面的 http://midjourney-proxy:8080
      MJ_SERVER:
      # midjourney API密钥，可选
      MJ_API_SECRET:
      #API_UPLOADER 是否可以上传 1 可以其他都不可以，可选
      API_UPLOADER:
      #HIDE_SERVER 隐藏服务端 1，可选
      HIDE_SERVER:
      #自定义模型  CUSTOM_MODELS=-gpt-3.5-turbo-0301,gpt-4.5 不显示 gpt-3.5-turbo-0301 新增加 gpt-4.5，可选
      CUSTOM_MODELS:
      #TJ_BAIDU_ID 百度统计ID，可选
      TJ_BAIDU_ID:
      #TJ_GOOGLE_ID 谷歌统计ID，可选
      TJ_GOOGLE_ID:
      #SYS_NOTIFY 系统通知 支持HTML ，可选
      SYS_NOTIFY:
      #FILE_SERVER 文件服务器，可选 可以用下面的 http://fileserver:3012
      FILE_SERVER: 
      #DISABLE_GPT4=1 前端限制GPT4调用，可选
      DISABLE_GPT4:
      # cloudflare r2 存储 10 GB/月 免费 https://www.cloudflare.com/zh-cn/developer-platform/r2/
      R2_DOMAIN:
      R2_BUCKET_NAME:
      R2_ACCOUNT_ID:
      R2_KEY_ID:
      R2_KEY_SECRET:
      ## UPLOAD_IMG_SIZE gpt-4-version 图片上传大小 单位是兆 注意别带单位 最好别超过10 
      UPLOAD_IMG_SIZE: 1
      # GPT_URL=/gpts.json  自定义GPTs模型
      GPT_URL:
      # SYS_THEME 主题 theme   light 或者 dark 
      SYS_THEME: dark
      #关闭MD预览  CLOSE_MD_PREVIEW=1
      CLOSE_MD_PREVIEW:
      #爆破：验证次数 注意: vercel 不支持 nginx 请设置  proxy_set_header   X-Forwarded-For  $remote_addr;
      AUTH_SECRET_ERROR_COUNT: 3
      #爆破：验证停留时间 单位分钟 注意: vercel 不支持
      AUTH_SECRET_ERROR_TIME: 10

